/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.frejt.piet;

public class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
